settings:
  colors:
    brand:
      blue:
        base: '#005ea2'
        light: '#73b3e7'
        light-1: '#d9e8f6'
        dark: '#1a4480'
        dark-1: '#162e51'
        vivid: '#0050d8'
      red:
        base: '#d83933'
        light: '#f2938c'
        light-1: '#f8dfe2'
        dark: '#b50909'
        dark-1: '#8b1303'
        vivid: '#e41d3d'
      blue-cool:
        base: '#00bde3'
        light: '#97d4ea'
        light-1: '#e1f3f8'
        dark: '#28a0cb'
        dark-1: '#07648d'
      orange:
        base: '#fa9441'
        light: '#ffbc78'
        light-1: '#fce2c5'
        dark: '#c05600'
        dark-1: '#775540'
    grayscale:
      white: '#ffffff'
      gray-1: '#f0f0f0'
      gray-2: '#dfe1e2'
      gray-3: '#a9aeb1'
      gray-4: '#71767a'
      gray-5: '#565c65'
      gray-6: '#3d4551'
      gray-7: '#171717'
      black: '#000000'
    other:
      blue-warm:
        20v: '#adcdff'
      indigo-cool:
        60v: '#3e4ded'
      indigo:
        20v: '#ccceff'
        30v: '#a3a7fa'
        60v: '#494fc9'
      violet:
        70v: '#54278f'
      red-warm:
        40v: '#ef5e25'
        50v: '#d54309'
      orange-warm:
        50v: '#cf4900'
      green-warm:
        5v: '#f5fbc1'
        10v: '#e7f434'
      green:
        10v: '#c5ee93'
      mint:
        10v: '#83fcd4'
        50v: '#2e8367'
      mint-cool:
        50v: '#40807e'
      cyan:
        20v: '#99deea'
        30v: '#5dc0d1'
  typography:
    font-family:
      body:
        name: 'Body'
        stack: '"Source Sans Pro Web", "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif'
      heading:
        name: 'Heading'
        stack: '"Merriweather Web", Georgia, Cambria, "Times New Roman", Times, serif'
      code:
        name: 'Code'
        stack: '"Roboto Mono Web", "Bitstream Vera Sans Mono", Consolas, Courier, monospace'
      ui:
        name: 'UI'
        stack: '"Source Sans Pro Web", "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif'
      alt:
        name: 'Alternate'
        stack: '"Merriweather Web", Georgia, Cambria, "Times New Roman", Times, serif'
    font-weight:
      light: 300
      normal: 400
      bold: 700
